### ISSUE TITLE
Congratulate

### ISSUE THREAD

**Issue by Payne-Wu** [Insutanto/scrapy-distributed#9]
As for distributed crawlers, I think it's just friendly URL management with reasonable scheduling rules. Semaphore will be their command gun, this is a really great open source project, looking forward to it。

Or we try to use `Raft`

**Comment by Insutanto** [comment]
Yes, I agree with you. In the beginning, `scrapy-distributed` was only a toy for me.
But, now I need your guy's advice and help to make this project help others.

**Comment by Payne-Wu** [comment]
My pleasure
我的荣幸
